apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: banking-platform-netpol
  namespace: banking
spec:
  podSelector:
    matchLabels:
      app: banking-platform
  policyTypes:
    - Ingress
    - Egress

  ingress:
    # Allow from NGINX ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
    # Allow from Prometheus scraping
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 8080

  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow outbound to databases
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: banking
      ports:
        - protocol: TCP
          port: 5432    # PostgreSQL
        - protocol: TCP
          port: 27017   # MongoDB
        - protocol: TCP
          port: 6379    # Redis
        - protocol: TCP
          port: 9092    # Kafka
    # Allow outbound to infra services
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: infra
      ports:
        - protocol: TCP
          port: 8200    # Vault
        - protocol: TCP
          port: 8500    # Consul
    # Allow outbound to Temporal
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: temporal
      ports:
        - protocol: TCP
          port: 7233
    # Allow outbound to observability
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 4317    # OTEL collector gRPC
    # Allow outbound HTTPS for webhooks and external APIs
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
